---
title: "GO_dotPlot"
author: "Pinji Lei"
date: "12/10/2018"
output: html_document
---


### GO functional analysis Biological Processes

```{r,echo=FALSE,message=FALSE}
library(dplyr)
library(ggplot2)
library(tidyr)
GO<-read.table(file = 'GO.BP.txt',header = T,sep = "\t")
pvalue_adj<--log10(GO$Bonferroni)
GO$pvalue_adj<-pvalue_adj
GO_top20<-GO[1:20,]
GO_top20<-GO_top20 %>%
  mutate(Term = factor(Term,levels = .$Term))
png(filename = "GO.BP.png",height = 3.6,width = 5.4,units = 'in',res = 300)
theme_set(theme_classic())
ggplot(GO_top20,aes(x=reorder(Term,pvalue_adj),y=pvalue_adj))+
  geom_point(color="tomato",size=3)+
  geom_segment(aes(x=Term,xend=Term,y=min(pvalue_adj),yend=max(pvalue_adj)),linetype="dashed",size=0.1)+
  xlab("Term")+
  ylab("-log10(Bonferroni Pvalue)")+
  coord_flip()
dev.off()
```

### KEGG pathway analysis

```{r,echo=FALSE,message=FALSE}
library(ggplot2)
library(tidyr)
KEGG<-read.table(file = 'KEGG.pathway.txt',header = T,sep = "\t")
pvalue_adj<--log10(KEGG$Bonferroni)
KEGG$pvalue_adj<-pvalue_adj
KEGG_top20<-KEGG[1:20,]
png(filename = "KEGG.pathway.png",height = 3.6,width = 5.4,units = 'in',res = 300)
theme_set(theme_classic())
ggplot(KEGG_top20,aes(x=reorder(Term,pvalue_adj),y=pvalue_adj))+
  geom_point(color="blue",size=3)+
  geom_segment(aes(x=Term,xend=Term,y=min(pvalue_adj),yend=max(pvalue_adj)),linetype="dashed",size=0.1)+
  xlab("Term")+
  ylab("-log10(Bonferroni Pvalue)")+
  coord_flip()
dev.off()
```

